api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    eager_loading:
      force_eager: false
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection: 
        pagination: 
            items_per_page: 3


#git add .
#git commit -m "commentaire"
#git push -u origine master